namespace: local
name: workstation
description: A collection of roles and playbooks to manage workstations
version: 0.1.0

authors:
  - 8ward <1367048+8ware@users.noreply.github.com>

readme: README.md
license_file: COPYING

repository: https://github.com/8ware/ansible-collection-workstation.git
issues: https://github.com/8ware/ansible-collection-workstation/issues
