---
- name: Un/install pipx
  ansible.builtin.apt:
    name: pipx
    state: "{{ workstation_apps_pipx_state }}"
  become: yes

- name: Install apps with pipx
  community.general.pipx:
    name: '{{ item }}'
  loop: '{{ workstation_apps_pipx }}'
