---
- name: Install pipx
  ansible.builtin.apt:
    name: pipx
  when: workstation_apps_pipx | length
  become: yes

- name: Install apps with pipx
  community.general.pipx:
    name: '{{ item }}'
  loop: '{{ workstation_apps_pipx }}'
